# Generated by Django 2.2 on 2019-04-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiction', '0003_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='delete_time',
        ),
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
