# Generated by Django 2.2 on 2019-04-06 08:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fiction', '0004_auto_20190406_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
